model:
    arch: segnet
data:
    dataset: camvid
    train_split: train
    val_split: val
    img_rows: 360
    img_cols: 480
    path: /home/alican/Datasets/CamVid2/
training:
    train_iters: 20000
    batch_size: 4
    val_interval: 1000
    n_workers: 8
    print_interval: 50
    optimizer:
        name: 'adam'
        lr: 1.0e-3
        weight_decay: 0.0005
        betas: [0.9, 0.999]
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
        name: 'multi_step'
        milestones: [10000,30000]
        gamma: 0.1
    resume: null